REL: add Trove classifier for Python 3
following the commits with titles:

> MAI: avoid unintentionally forming unicode escape sequence

and:

> MAI: pass `universal_newlines=True` to `subprocess.Popen`

Note that using recent Python 3.* versions appears to
require `networkx >= 2.4`, due to an error raised by
earlier `networkx` versions:

```
ImportError: cannot import name 'gcd' from 'fractions'
(/.../lib/python3.9/fractions.py)
```

So adding classifiers for those Python versions requires
first updating `nx2tikz` to be compatible with
`networkx >= 2.0.0`.

Also, remove the Trove classifier that signifies
compatibility to only Python 2.