REL: rm upper bound `networkx < 2.0.0` from `install_requires`
because now compatible with both `networkx >= 2.0.0` and
`networkx < 2.0.0`. Using `networkx < 2.0.0` requires also
using a compatible Python version.

For example, `networkx==1.11` is compatible with
Python 2.7, 3.3, 3.4, 3.5, according to
the Trove classifiers of [that `networkx` version](
    https://pypi.org/project/networkx/1.11/)

To use a newer Python version, a higher `networkx` version
may be needed. For example, to use Python 3.9,
`networkx >= 2.4` appears necessary, because earlier `networkx`
versions raise an error:

```
ImportError: cannot import name 'gcd' from 'fractions'
(/.../lib/python3.9/fractions.py)
```

Therefore, this update to the API of `networkx >= 2.0.0`
also enables using higher Python 3.* versions.

(`networkx >= 2.4` appears to work with Python 3.9,
even though the Trove classifiers of `netwokx == 2.4` do
not include Python 3.9.)

Also, note in file `README.md` that Python 2 requires
`networkx <= 2.2`.